title: Nordhaven Tails
description: Tails told from the great Nordhaven Lodge

markdown: kramdown
theme: minima # Or your chosen theme
plugins:
  - jekyll-feed
  - jekyll-seo-tag

collections:
  posts:
    permalink: /posts/:year/:month/:day/:title/
    output: true

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

include:
  - .htaccess
