title: Nordhaven Tails
description: Tails told from the great Nordhaven Lodge

theme: minima

search_enabled: true

markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

collections:
  posts:
    permalink: /posts/:year/:month/:day/:title/
    output: true
