title: Nordhaven Tails
description: Tails told from the great Nordhaven Lodge
remote_theme: zendesk/jekyll-theme-zendesk-garden@main

search_enabled: true

markdown: kramdown
theme: minima # Or your chosen theme
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-remote-theme

collections:
  posts:
    permalink: /posts/:year/:month/:day/:title/
    output: true

sidebar:
  - ai-ml
  - label: Computing
    children:
      - computing-resources-overview
      - hpcc
      - ursa-major
      - nsf-access
      - nautilus
      - nsf-osg
      - gcp-aws-edp
      - gcp-aws-cloud-credits
      - on-prem-facilities
  - label: Data Storage
    children:
      - storage-overview
      - ursa-major-storage
      - google-drive
      - ursa-major-data
      - gcs-aws-s3
      - hpcc-gpfs
      - ceph-secure-research-storage
      - dryad
      - backup
  - label: Support
    children:
      - research-facilitation
      - software-support
      - infrastructure-support
      - grant-collaboration
      - lab-support
  - label: Training
    children:
      - workshops-and-webinars
      - online-courses
      - documentation-and-guides
  - research-security
  - knowledge-base
  - cost-models
  - guidelines
  - about
  - success-stories
  - contact-us
