title: Nordhaven
description: Tails told from the Great Nordhaven Lodge
remote_theme: zendesk/jekyll-theme-zendesk-garden@main

search_enabled: true

markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-remote-theme
