title: Nordhaven
description: Tales told from the Great Nordhaven Lodge
remote_theme: zendesk/jekyll-theme-zendesk-garden@main

search_enabled: true
permalink: /:year/:month/:day/:title.html

markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-remote-theme
